### ISSUE TITLE
Very interesting work

### ISSUE THREAD

**Issue by linzhiqiu** [BeierZhu/GLA#1]
Congrats on your interesting NeurIPS paper!

By the way, we do have a simple few-shot baseline using linear-probing on both image and text features, and it surpasses prior prompting (CoOp/ProGrad) methods across 1 to 16 shots with significantly less training time (2min versus CoOp's 14 hours): https://arxiv.org/pdf/2301.06267.pdf

**Comment by BeierZhu** [comment]
Hi Zhiqiu,

I just went through your paper. I like your method and its connection to ensembling brings insights to me. I am impressed by the performance and speed of your method. I regret not having read your paper earlier. If given the opportunity, I will update our baselines with your method. Thank you for your recommendation.

**Comment by linzhiqiu** [comment]
Hey Beier,

Thanks for your kind words! We also love your paper and will follow up on this work :-)
